[package]
name = "lndb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs4 = "0.7.0"
log = "0.4.20"
serde_derive = "1.0.195"
tempdir = "0.3.7"
